Warning: Permanently added '[localhost]:3022' (ED25519) to the list of known hosts.
#0 building with "default" instance using docker driver

#1 [internal] load build definition from Dockerfile
#1 transferring dockerfile: 534B done
#1 DONE 0.1s

#2 [internal] load metadata for docker.io/library/python:3.8
#2 DONE 0.8s

#3 [internal] load .dockerignore
#3 transferring context: 2B done
#3 DONE 0.1s

#4 [1/5] FROM docker.io/library/python:3.8@sha256:01a4da15f16395a2d17dd9b673ccedcd6a6dbb4e130c8056d0d804dedac11c81
#4 DONE 0.0s

#5 [2/5] WORKDIR /app
#5 CACHED

#6 [3/5] RUN git clone https://github.com/boppreh/keyboard.git .
#6 0.303 Cloning into '.'...
#6 DONE 2.3s

#7 [4/5] RUN make build
#7 0.372 python2 -m coverage run -m keyboard._keyboard_tests
#7 0.372 make: python2: No such file or directory
#7 0.372 make: *** [Makefile:3: tests] Error 127
#7 ERROR: process "/bin/sh -c make build" did not complete successfully: exit code: 2
------
 > [4/5] RUN make build:
0.372 python2 -m coverage run -m keyboard._keyboard_tests
0.372 make: python2: No such file or directory
0.372 make: *** [Makefile:3: tests] Error 127
------
Dockerfile:15
--------------------
  13 |     # Based on the Makefile contents, it seems that the installation steps are integrated into the make tasks.
  14 |     # We can execute the build task to take care of installation.
  15 | >>> RUN make build
  16 |     
  17 |     # Run tests to verify the installation
--------------------
ERROR: failed to solve: process "/bin/sh -c make build" did not complete successfully: exit code: 2
removing docker image...clearing temp directorymachine already started
TEMP DIR: /tmp/tmp.bmFkF4uSft


Warning: Permanently added '[localhost]:3022' (ED25519) to the list of known hosts.
#0 building with "default" instance using docker driver

#1 [internal] load build definition from Dockerfile
#1 transferring dockerfile: 297B done
#1 DONE 0.1s

#2 [internal] load metadata for docker.io/library/python:3.8
#2 DONE 0.8s

#3 [internal] load .dockerignore
#3 transferring context: 2B done
#3 DONE 0.1s

#4 [1/3] FROM docker.io/library/python:3.8@sha256:01a4da15f16395a2d17dd9b673ccedcd6a6dbb4e130c8056d0d804dedac11c81
#4 DONE 0.0s

#5 [2/3] WORKDIR /app
#5 CACHED

#6 [internal] load build context
#6 transferring context: 297B done
#6 DONE 0.1s

#7 [3/3] COPY . /app
#7 DONE 0.1s

#8 exporting to image
#8 exporting layers 0.1s done
#8 writing image sha256:d4af6ef42bdb95c1b6dcaca819201eaa277ba930dc21c8109b33846dc471ef6e done
#8 naming to docker.io/library/temp_image done
#8 DONE 0.1s
Docker build completed successfully on virtual machine.
removing docker image...
clearing temp directory
machine already started
TEMP DIR: /tmp/tmp.ebS6xsh9ch


Warning: Permanently added '[localhost]:3022' (ED25519) to the list of known hosts.
#0 building with "default" instance using docker driver

#1 [internal] load build definition from Dockerfile
#1 transferring dockerfile: 288B done
#1 DONE 0.1s

#2 [internal] load metadata for docker.io/library/python:3.8
#2 DONE 0.8s

#3 [internal] load .dockerignore
#3 transferring context: 2B done
#3 DONE 0.1s

#4 [1/4] FROM docker.io/library/python:3.8@sha256:01a4da15f16395a2d17dd9b673ccedcd6a6dbb4e130c8056d0d804dedac11c81
#4 DONE 0.0s

#5 [2/4] WORKDIR /app
#5 CACHED

#6 [internal] load build context
#6 transferring context: 288B done
#6 DONE 0.1s

#7 [3/4] COPY . /app
#7 DONE 0.1s

#8 [4/4] RUN python setup.py test
#8 0.308 python: can't open file 'setup.py': [Errno 2] No such file or directory
#8 ERROR: process "/bin/sh -c python setup.py test" did not complete successfully: exit code: 2
------
 > [4/4] RUN python setup.py test:
0.308 python: can't open file 'setup.py': [Errno 2] No such file or directory
------
Dockerfile:11
--------------------
   9 |     
  10 |     # Run the test suite
  11 | >>> RUN python setup.py test
  12 |     
--------------------
ERROR: failed to solve: process "/bin/sh -c python setup.py test" did not complete successfully: exit code: 2
removing docker image...
clearing temp directory
machine already started
TEMP DIR: /tmp/tmp.Qg9yN9BiIq


Warning: Permanently added '[localhost]:3022' (ED25519) to the list of known hosts.
#0 building with "default" instance using docker driver

#1 [internal] load build definition from Dockerfile
#1 transferring dockerfile: 270B done
#1 DONE 0.1s

#2 [internal] load metadata for docker.io/library/python:3.9
#2 DONE 0.7s

#3 [internal] load .dockerignore
#3 transferring context: 2B done
#3 DONE 0.1s

#4 [1/4] FROM docker.io/library/python:3.9@sha256:1446afd121c574b13077f4137443114cd8085f1dade5ee63c08305b5870f2b8a
#4 DONE 0.0s

#5 [2/4] WORKDIR /app
#5 CACHED

#6 [internal] load build context
#6 transferring context: 270B done
#6 DONE 0.1s

#7 [3/4] COPY . /app
#7 DONE 0.1s

#8 [4/4] RUN python setup.py test
#8 0.343 python: can't open file '/app/setup.py': [Errno 2] No such file or directory
#8 ERROR: process "/bin/sh -c python setup.py test" did not complete successfully: exit code: 2
------
 > [4/4] RUN python setup.py test:
0.343 python: can't open file '/app/setup.py': [Errno 2] No such file or directory
------
Dockerfile:11
--------------------
   9 |     
  10 |     # Run the test suite
  11 | >>> RUN python setup.py test
  12 |     
--------------------
ERROR: failed to solve: process "/bin/sh -c python setup.py test" did not complete successfully: exit code: 2
removing docker image...
clearing temp directory
machine already started
TEMP DIR: /tmp/tmp.TYEU37zPiO


Warning: Permanently added '[localhost]:3022' (ED25519) to the list of known hosts.
#0 building with "default" instance using docker driver

#1 [internal] load build definition from Dockerfile
#1 transferring dockerfile: 334B done
#1 DONE 0.1s

#2 [internal] load metadata for docker.io/library/python:3.8
#2 ...

#3 [auth] library/python:pull token for registry-1.docker.io
#3 DONE 0.0s

#2 [internal] load metadata for docker.io/library/python:3.8
#2 DONE 1.4s

#4 [internal] load .dockerignore
#4 transferring context: 2B done
#4 DONE 0.1s

#5 [1/4] FROM docker.io/library/python:3.8@sha256:01a4da15f16395a2d17dd9b673ccedcd6a6dbb4e130c8056d0d804dedac11c81
#5 DONE 0.0s

#6 [2/4] WORKDIR /app
#6 CACHED

#7 [internal] load build context
#7 transferring context: 334B done
#7 DONE 0.1s

#8 [3/4] COPY . /app
#8 DONE 0.1s

#9 [4/4] RUN python setup.py install
#9 0.354 python: can't open file 'setup.py': [Errno 2] No such file or directory
#9 ERROR: process "/bin/sh -c python setup.py install" did not complete successfully: exit code: 2
------
 > [4/4] RUN python setup.py install:
0.354 python: can't open file 'setup.py': [Errno 2] No such file or directory
------
Dockerfile:10
--------------------
   8 |     
   9 |     # Install the repository
  10 | >>> RUN python setup.py install
  11 |     
  12 |     # Run the test suite
--------------------
ERROR: failed to solve: process "/bin/sh -c python setup.py install" did not complete successfully: exit code: 2
removing docker image...
clearing temp directory
machine already started
TEMP DIR: /tmp/tmp.iP6FDvftJD


Warning: Permanently added '[localhost]:3022' (ED25519) to the list of known hosts.
#0 building with "default" instance using docker driver

#1 [internal] load build definition from Dockerfile
#1 transferring dockerfile: 288B done
#1 DONE 0.1s

#2 [internal] load metadata for docker.io/library/python:3.8
#2 DONE 0.7s

#3 [internal] load .dockerignore
#3 transferring context: 2B done
#3 DONE 0.1s

#4 [1/4] FROM docker.io/library/python:3.8@sha256:01a4da15f16395a2d17dd9b673ccedcd6a6dbb4e130c8056d0d804dedac11c81
#4 DONE 0.0s

#5 [2/4] WORKDIR /app
#5 CACHED

#6 [internal] load build context
#6 transferring context: 288B done
#6 DONE 0.1s

#7 [3/4] COPY . /app
#7 DONE 0.1s

#8 [4/4] RUN python setup.py test
#8 0.316 python: can't open file 'setup.py': [Errno 2] No such file or directory
#8 ERROR: process "/bin/sh -c python setup.py test" did not complete successfully: exit code: 2
------
 > [4/4] RUN python setup.py test:
0.316 python: can't open file 'setup.py': [Errno 2] No such file or directory
------
Dockerfile:11
--------------------
   9 |     
  10 |     # Run the test suite
  11 | >>> RUN python setup.py test
  12 |     
--------------------
ERROR: failed to solve: process "/bin/sh -c python setup.py test" did not complete successfully: exit code: 2
removing docker image...
clearing temp directory
machine already started
TEMP DIR: /tmp/tmp.mzSNGGUVlG


Warning: Permanently added '[localhost]:3022' (ED25519) to the list of known hosts.
#0 building with "default" instance using docker driver

#1 [internal] load build definition from Dockerfile
#1 transferring dockerfile: 315B done
#1 DONE 0.1s

#2 [internal] load metadata for docker.io/library/python:3.8
#2 DONE 0.7s

#3 [internal] load .dockerignore
#3 transferring context: 2B done
#3 DONE 0.1s

#4 [1/4] FROM docker.io/library/python:3.8@sha256:01a4da15f16395a2d17dd9b673ccedcd6a6dbb4e130c8056d0d804dedac11c81
#4 DONE 0.0s

#5 [2/4] WORKDIR /app
#5 CACHED

#6 [internal] load build context
#6 transferring context: 315B done
#6 DONE 0.1s

#7 [3/4] COPY . /app
#7 DONE 0.2s

#8 [4/4] RUN python setup.py test
#8 0.553 python: can't open file 'setup.py': [Errno 2] No such file or directory
#8 ERROR: process "/bin/sh -c python setup.py test" did not complete successfully: exit code: 2
------
 > [4/4] RUN python setup.py test:
0.553 python: can't open file 'setup.py': [Errno 2] No such file or directory
------
Dockerfile:11
--------------------
   9 |     
  10 |     # Run the test suite to verify the installation
  11 | >>> RUN python setup.py test
  12 |     
--------------------
ERROR: failed to solve: process "/bin/sh -c python setup.py test" did not complete successfully: exit code: 2
removing docker image...
clearing temp directory
machine already started
TEMP DIR: /tmp/tmp.HDVwZh4fhm


Warning: Permanently added '[localhost]:3022' (ED25519) to the list of known hosts.
#0 building with "default" instance using docker driver

#1 [internal] load build definition from Dockerfile
#1 transferring dockerfile: 238B done
#1 DONE 0.1s

#2 [internal] load metadata for docker.io/library/python:3.8
#2 DONE 0.7s

#3 [internal] load .dockerignore
#3 transferring context: 2B done
#3 DONE 0.1s

#4 [1/4] FROM docker.io/library/python:3.8@sha256:01a4da15f16395a2d17dd9b673ccedcd6a6dbb4e130c8056d0d804dedac11c81
#4 DONE 0.0s

#5 [2/4] WORKDIR /app
#5 CACHED

#6 [internal] load build context
#6 transferring context: 238B done
#6 DONE 0.1s

#7 [3/4] COPY . /app
#7 DONE 0.1s

#8 [4/4] RUN python setup.py test
#8 0.526 python: can't open file 'setup.py': [Errno 2] No such file or directory
#8 ERROR: process "/bin/sh -c python setup.py test" did not complete successfully: exit code: 2
------
 > [4/4] RUN python setup.py test:
0.526 python: can't open file 'setup.py': [Errno 2] No such file or directory
------
Dockerfile:10
--------------------
   8 |     
   9 |     # Run the test suite
  10 | >>> RUN python setup.py test
--------------------
ERROR: failed to solve: process "/bin/sh -c python setup.py test" did not complete successfully: exit code: 2
removing docker image...
clearing temp directory
machine already started
TEMP DIR: /tmp/tmp.48nhm2dSVD


Warning: Permanently added '[localhost]:3022' (ED25519) to the list of known hosts.
#0 building with "default" instance using docker driver

#1 [internal] load build definition from Dockerfile
#1 transferring dockerfile: 420B done
#1 DONE 0.1s

#2 [internal] load metadata for docker.io/library/python:3.8
#2 DONE 0.8s

#3 [internal] load .dockerignore
#3 transferring context: 2B done
#3 DONE 0.1s

#4 [1/5] FROM docker.io/library/python:3.8@sha256:01a4da15f16395a2d17dd9b673ccedcd6a6dbb4e130c8056d0d804dedac11c81
#4 DONE 0.0s

#5 [2/5] WORKDIR /app
#5 CACHED

#6 [3/5] RUN git clone https://github.com/your-username/your-repo.git
#6 0.311 Cloning into 'your-repo'...
#6 0.783 fatal: could not read Username for 'https://github.com': No such device or address
#6 ERROR: process "/bin/sh -c git clone https://github.com/your-username/your-repo.git" did not complete successfully: exit code: 128
------
 > [3/5] RUN git clone https://github.com/your-username/your-repo.git:
0.311 Cloning into 'your-repo'...
0.783 fatal: could not read Username for 'https://github.com': No such device or address
------
Dockerfile:8
--------------------
   6 |     
   7 |     # Clone the repository from the source
   8 | >>> RUN git clone https://github.com/your-username/your-repo.git
   9 |     
  10 |     # Set the working directory to the cloned repository
--------------------
ERROR: failed to solve: process "/bin/sh -c git clone https://github.com/your-username/your-repo.git" did not complete successfully: exit code: 128
removing docker image...
clearing temp directory
machine already started
TEMP DIR: 


Warning: Permanently added '[localhost]:3022' (ED25519) to the list of known hosts.
ERROR: failed to update builder last activity time: write /home/machine/.docker/buildx/activity/.tmp-default1815221369: no space left on device
removing docker image...
clearing temp directory
