Warning: Permanently added '[localhost]:3022' (ED25519) to the list of known hosts.
#0 building with "default" instance using docker driver

#1 [internal] load build definition from Dockerfile
#1 transferring dockerfile: 290B done
#1 DONE 0.1s

#2 [internal] load metadata for docker.io/library/python:3.8
#2 DONE 0.7s

#3 [internal] load .dockerignore
#3 transferring context: 2B done
#3 DONE 0.1s

#4 [1/6] FROM docker.io/library/python:3.8@sha256:01a4da15f16395a2d17dd9b673ccedcd6a6dbb4e130c8056d0d804dedac11c81
#4 CACHED

#5 [internal] load build context
#5 transferring context: 2B done
#5 DONE 0.2s

#6 [2/6] RUN git clone https://github.com/jhao104/proxy_pool.git /app
#6 ...

#7 [3/6] WORKDIR /app
#7 CACHED

#8 [4/6] COPY requirements.txt ./
#8 ERROR: failed to calculate checksum of ref 40bc7d34-f251-4a8c-9b64-40dd406c9169::r238lhob2d19v3wwg16a1jxkx: "/requirements.txt": not found

#6 [2/6] RUN git clone https://github.com/jhao104/proxy_pool.git /app
#6 0.370 Cloning into '/app'...
#6 DONE 1.8s
------
 > [4/6] COPY requirements.txt ./:
------
Dockerfile:8
--------------------
   6 |     
   7 |     # Install any necessary dependencies
   8 | >>> copy requirements.txt ./
   9 |     RUN pip install --no-cache-dir -r requirements.txt
  10 |     
--------------------
ERROR: failed to solve: failed to compute cache key: failed to calculate checksum of ref 40bc7d34-f251-4a8c-9b64-40dd406c9169::r238lhob2d19v3wwg16a1jxkx: "/requirements.txt": not found
removing docker image...clearing temp directorymachine already startedTEMP DIR: /tmp/tmp.9NTaFpfgFTWarning: Permanently added '[localhost]:3022' (ED25519) to the list of known hosts.
#0 building with "default" instance using docker driver

#1 [internal] load build definition from Dockerfile
#1 transferring dockerfile: 438B done
#1 DONE 0.1s

#2 [auth] library/python:pull token for registry-1.docker.io
#2 DONE 0.0s

#3 [internal] load metadata for docker.io/library/python:3.8
#3 DONE 1.4s

#4 [internal] load .dockerignore
#4 transferring context: 2B done
#4 DONE 0.1s

#5 [1/6] FROM docker.io/library/python:3.8@sha256:01a4da15f16395a2d17dd9b673ccedcd6a6dbb4e130c8056d0d804dedac11c81
#5 DONE 0.0s

#6 [2/6] WORKDIR /app
#6 CACHED

#7 [3/6] RUN git clone https://github.com/jhao104/proxy_pool.git
#7 0.279 Cloning into 'proxy_pool'...
#7 DONE 2.2s

#8 [4/6] WORKDIR /app/proxy_pool
#8 DONE 0.1s

#9 [5/6] RUN pip install -r requirements.txt
#9 1.287 Ignoring APScheduler: markers 'python_version >= "3.10"' don't match your environment
#9 1.288 Ignoring click: markers 'python_version <= "3.6"' don't match your environment
#9 1.289 Ignoring Flask: markers 'python_version <= "3.6"' don't match your environment
#9 1.289 Ignoring werkzeug: markers 'python_version <= "3.6"' don't match your environment
#9 1.452 Collecting requests==2.20.0
#9 1.507   Downloading requests-2.20.0-py2.py3-none-any.whl (60 kB)
#9 1.548      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.0/61.0 kB 1.3 MB/s eta 0:00:00
#9 1.605 Collecting gunicorn==19.9.0
#9 1.625   Downloading gunicorn-19.9.0-py2.py3-none-any.whl (112 kB)
#9 1.669      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 112.9/112.9 kB 3.1 MB/s eta 0:00:00
#9 2.096 Collecting lxml==4.9.2
#9 2.109   Downloading lxml-4.9.2-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.manylinux_2_24_x86_64.whl (7.1 MB)
#9 5.593      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.1/7.1 MB 2.0 MB/s eta 0:00:00
#9 5.689 Collecting redis==3.5.3
#9 5.706   Downloading redis-3.5.3-py2.py3-none-any.whl (72 kB)
#9 5.740      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 72.1/72.1 kB 1.9 MB/s eta 0:00:00
#9 5.798 Collecting APScheduler==3.2.0
#9 5.818   Downloading APScheduler-3.2.0-py2.py3-none-any.whl (52 kB)
#9 5.873      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 52.2/52.2 kB 1.1 MB/s eta 0:00:00
#9 5.957 Collecting click==8.0.1
#9 5.967   Downloading click-8.0.1-py3-none-any.whl (97 kB)
#9 6.040      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 97.4/97.4 kB 1.8 MB/s eta 0:00:00
#9 6.135 Collecting Flask==2.1.1
#9 6.152   Downloading Flask-2.1.1-py3-none-any.whl (95 kB)
#9 6.197      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 95.2/95.2 kB 2.2 MB/s eta 0:00:00
#9 6.256 Collecting werkzeug==2.1.0
#9 6.269   Downloading Werkzeug-2.1.0-py3-none-any.whl (224 kB)
#9 6.365      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 224.6/224.6 kB 2.3 MB/s eta 0:00:00
#9 6.442 Collecting urllib3<1.25,>=1.21.1
#9 6.456   Downloading urllib3-1.24.3-py2.py3-none-any.whl (118 kB)
#9 6.497      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 118.8/118.8 kB 3.1 MB/s eta 0:00:00
#9 6.532 Collecting chardet<3.1.0,>=3.0.2
#9 6.543   Downloading chardet-3.0.4-py2.py3-none-any.whl (133 kB)
#9 6.603      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 133.4/133.4 kB 3.2 MB/s eta 0:00:00
#9 6.634 Collecting idna<2.8,>=2.5
#9 6.646   Downloading idna-2.7-py2.py3-none-any.whl (58 kB)
#9 6.677      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 58.2/58.2 kB 1.7 MB/s eta 0:00:00
#9 6.755 Collecting certifi>=2017.4.17
#9 6.769   Downloading certifi-2024.2.2-py3-none-any.whl (163 kB)
#9 6.814      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 163.8/163.8 kB 3.8 MB/s eta 0:00:00
#9 6.832 Requirement already satisfied: setuptools>=0.7 in /usr/local/lib/python3.8/site-packages (from APScheduler==3.2.0->-r requirements.txt (line 6)) (57.5.0)
#9 6.868 Collecting six>=1.4.0
#9 6.876   Downloading six-1.16.0-py2.py3-none-any.whl (11 kB)
#9 6.977 Collecting pytz
#9 6.986   Downloading pytz-2024.1-py2.py3-none-any.whl (505 kB)
#9 7.192      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 505.5/505.5 kB 2.6 MB/s eta 0:00:00
#9 7.246 Collecting tzlocal>=1.2
#9 7.264   Downloading tzlocal-5.2-py3-none-any.whl (17 kB)
#9 7.322 Collecting Jinja2>=3.0
#9 7.332   Downloading jinja2-3.1.4-py3-none-any.whl (133 kB)
#9 7.403      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 133.3/133.3 kB 1.8 MB/s eta 0:00:00
#9 7.437 Collecting itsdangerous>=2.0
#9 7.451   Downloading itsdangerous-2.2.0-py3-none-any.whl (16 kB)
#9 7.589 Collecting importlib-metadata>=3.6.0
#9 7.598   Downloading importlib_metadata-7.1.0-py3-none-any.whl (24 kB)
#9 7.685 Collecting zipp>=0.5
#9 7.706   Downloading zipp-3.18.2-py3-none-any.whl (8.3 kB)
#9 7.859 Collecting MarkupSafe>=2.0
#9 7.872   Downloading MarkupSafe-2.1.5-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (26 kB)
#9 7.950 Collecting backports.zoneinfo
#9 7.962   Downloading backports.zoneinfo-0.2.1-cp38-cp38-manylinux1_x86_64.whl (74 kB)
#9 7.998      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 74.0/74.0 kB 3.8 MB/s eta 0:00:00
#9 8.128 Installing collected packages: pytz, idna, chardet, zipp, werkzeug, urllib3, six, redis, MarkupSafe, lxml, itsdangerous, gunicorn, click, certifi, backports.zoneinfo, tzlocal, requests, Jinja2, importlib-metadata, Flask, APScheduler
#9 9.190 Successfully installed APScheduler-3.2.0 Flask-2.1.1 Jinja2-3.1.4 MarkupSafe-2.1.5 backports.zoneinfo-0.2.1 certifi-2024.2.2 chardet-3.0.4 click-8.0.1 gunicorn-19.9.0 idna-2.7 importlib-metadata-7.1.0 itsdangerous-2.2.0 lxml-4.9.2 pytz-2024.1 redis-3.5.3 requests-2.20.0 six-1.16.0 tzlocal-5.2 urllib3-1.24.3 werkzeug-2.1.0 zipp-3.18.2
#9 9.191 WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
#9 9.321 
#9 9.321 [notice] A new release of pip is available: 23.0.1 -> 24.0
#9 9.321 [notice] To update, run: pip install --upgrade pip
#9 DONE 9.5s

#10 [6/6] RUN pytest
#10 0.343 /bin/sh: 1: pytest: not found
#10 ERROR: process "/bin/sh -c pytest" did not complete successfully: exit code: 127
------
 > [6/6] RUN pytest:
pytest: not found
------
Dockerfile:17
--------------------
  15 |     
  16 |     # Run tests to verify installation
  17 | >>> RUN pytest
--------------------
ERROR: failed to solve: process "/bin/sh -c pytest" did not complete successfully: exit code: 127
removing docker image...clearing temp directorymachine already started
TEMP DIR: /tmp/tmp.PYvO1g7jml


Warning: Permanently added '[localhost]:3022' (ED25519) to the list of known hosts.
#0 building with "default" instance using docker driver

#1 [internal] load build definition from Dockerfile
#1 transferring dockerfile: 330B done
#1 DONE 0.1s

#2 [internal] load metadata for docker.io/library/python:3.8
#2 DONE 0.8s

#3 [internal] load .dockerignore
#3 transferring context: 2B done
#3 DONE 0.1s

#4 [1/7] FROM docker.io/library/python:3.8@sha256:01a4da15f16395a2d17dd9b673ccedcd6a6dbb4e130c8056d0d804dedac11c81
#4 DONE 0.0s

#5 [2/7] WORKDIR /app
#5 CACHED

#6 [internal] load build context
#6 transferring context: 330B 0.0s done
#6 DONE 0.2s

#7 [3/7] RUN git clone https://github.com/jhao104/proxy_pool.git .
#7 ...

#8 [4/7] COPY requirements.txt ./
#8 ERROR: failed to calculate checksum of ref 40bc7d34-f251-4a8c-9b64-40dd406c9169::s3prhtugbhkm2d4y3mps4idaf: "/requirements.txt": not found

#7 [3/7] RUN git clone https://github.com/jhao104/proxy_pool.git .
#7 CANCELED
------
 > [4/7] COPY requirements.txt ./:
------
Dockerfile:11
--------------------
   9 |     
  10 |     # Install dependencies
  11 | >>> COPY requirements.txt ./
  12 |     RUN pip install -r requirements.txt
  13 |     
--------------------
ERROR: failed to solve: failed to compute cache key: failed to calculate checksum of ref 40bc7d34-f251-4a8c-9b64-40dd406c9169::s3prhtugbhkm2d4y3mps4idaf: "/requirements.txt": not found
removing docker image...
clearing temp directory
machine already started
TEMP DIR: /tmp/tmp.xvqZDkOrZo


Warning: Permanently added '[localhost]:3022' (ED25519) to the list of known hosts.
#0 building with "default" instance using docker driver

#1 [internal] load build definition from Dockerfile
#1 transferring dockerfile: 345B done
#1 DONE 0.1s

#2 [internal] load metadata for docker.io/library/python:3.8
#2 DONE 0.8s

#3 [internal] load .dockerignore
#3 transferring context: 2B done
#3 DONE 0.1s

#4 [1/4] FROM docker.io/library/python:3.8@sha256:01a4da15f16395a2d17dd9b673ccedcd6a6dbb4e130c8056d0d804dedac11c81
#4 DONE 0.0s

#5 [2/4] WORKDIR /app
#5 CACHED

#6 [internal] load build context
#6 transferring context: 345B done
#6 DONE 0.1s

#7 [3/4] COPY . /app
#7 DONE 0.2s

#8 [4/4] RUN pip install -r requirements.txt
#8 1.246 ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'
#8 1.442 
#8 1.442 [notice] A new release of pip is available: 23.0.1 -> 24.0
#8 1.442 [notice] To update, run: pip install --upgrade pip
#8 ERROR: process "/bin/sh -c pip install -r requirements.txt" did not complete successfully: exit code: 1
------
 > [4/4] RUN pip install -r requirements.txt:
1.246 ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'
1.442 
1.442 [notice] A new release of pip is available: 23.0.1 -> 24.0
1.442 [notice] To update, run: pip install --upgrade pip
------
Dockerfile:11
--------------------
   9 |     
  10 |     # Install the project dependencies
  11 | >>> RUN pip install -r requirements.txt
  12 |     
  13 |     # Run the test suite
--------------------
ERROR: failed to solve: process "/bin/sh -c pip install -r requirements.txt" did not complete successfully: exit code: 1
removing docker image...
clearing temp directory
machine already started
TEMP DIR: /tmp/tmp.y57WQxfKQr


Warning: Permanently added '[localhost]:3022' (ED25519) to the list of known hosts.
#0 building with "default" instance using docker driver

#1 [internal] load build definition from Dockerfile
#1 transferring dockerfile: 394B done
#1 DONE 0.1s

#2 [internal] load metadata for docker.io/library/python:3.8
#2 DONE 0.8s

#3 [internal] load .dockerignore
#3 transferring context: 2B done
#3 DONE 0.1s

#4 [1/5] FROM docker.io/library/python:3.8@sha256:01a4da15f16395a2d17dd9b673ccedcd6a6dbb4e130c8056d0d804dedac11c81
#4 DONE 0.0s

#5 [2/5] WORKDIR /app
#5 CACHED

#6 [internal] load build context
#6 transferring context: 394B done
#6 DONE 0.1s

#7 [3/5] COPY . /app
#7 DONE 0.1s

#8 [4/5] RUN pip install --no-cache-dir -r requirements.txt
#8 1.396 ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'
#8 1.524 
#8 1.524 [notice] A new release of pip is available: 23.0.1 -> 24.0
#8 1.524 [notice] To update, run: pip install --upgrade pip
#8 ERROR: process "/bin/sh -c pip install --no-cache-dir -r requirements.txt" did not complete successfully: exit code: 1
------
 > [4/5] RUN pip install --no-cache-dir -r requirements.txt:
1.396 ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'
1.524 
1.524 [notice] A new release of pip is available: 23.0.1 -> 24.0
1.524 [notice] To update, run: pip install --upgrade pip
------
Dockerfile:11
--------------------
   9 |     
  10 |     # Install any needed packages specified in requirements.txt
  11 | >>> RUN pip install --no-cache-dir -r requirements.txt
  12 |     
  13 |     # Run the test suite
--------------------
ERROR: failed to solve: process "/bin/sh -c pip install --no-cache-dir -r requirements.txt" did not complete successfully: exit code: 1
removing docker image...
clearing temp directory
machine already started
TEMP DIR: /tmp/tmp.yGam7dVd6u


Warning: Permanently added '[localhost]:3022' (ED25519) to the list of known hosts.
#0 building with "default" instance using docker driver

#1 [internal] load build definition from Dockerfile
#1 transferring dockerfile: 350B done
#1 DONE 0.1s

#2 [internal] load metadata for docker.io/library/python:3
#2 DONE 0.8s

#3 [internal] load .dockerignore
#3 transferring context: 2B done
#3 DONE 0.1s

#4 [1/4] FROM docker.io/library/python:3@sha256:3966b81808d864099f802080d897cef36c01550472ab3955fdd716d1c665acd6
#4 DONE 0.0s

#5 [2/4] WORKDIR /app
#5 CACHED

#6 [internal] load build context
#6 transferring context: 350B done
#6 DONE 0.1s

#7 [3/4] COPY . /app
#7 DONE 0.1s

#8 [4/4] RUN pip install -r requirements.txt
#8 1.483 ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'
#8 ERROR: process "/bin/sh -c pip install -r requirements.txt" did not complete successfully: exit code: 1
------
 > [4/4] RUN pip install -r requirements.txt:
1.483 ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'
------
Dockerfile:11
--------------------
   9 |     
  10 |     # Install the project dependencies
  11 | >>> RUN pip install -r requirements.txt
  12 |     
  13 |     # Run the test suite
--------------------
ERROR: failed to solve: process "/bin/sh -c pip install -r requirements.txt" did not complete successfully: exit code: 1
removing docker image...
clearing temp directory
machine already started
TEMP DIR: /tmp/tmp.LPirNNPrx7


Warning: Permanently added '[localhost]:3022' (ED25519) to the list of known hosts.
#0 building with "default" instance using docker driver

#1 [internal] load build definition from Dockerfile
#1 transferring dockerfile: 651B done
#1 DONE 0.1s

#2 [internal] load metadata for docker.io/library/python:3.6-alpine
#2 DONE 2.1s

#3 [internal] load .dockerignore
#3 transferring context: 2B done
#3 DONE 0.1s

#4 [internal] load build context
#4 transferring context: 651B done
#4 DONE 0.1s

#5 [1/7] FROM docker.io/library/python:3.6-alpine@sha256:579978dec4602646fe1262f02b96371779bfb0294e92c91392707fa999c0c989
#5 resolve docker.io/library/python:3.6-alpine@sha256:579978dec4602646fe1262f02b96371779bfb0294e92c91392707fa999c0c989 0.1s done
#5 sha256:579978dec4602646fe1262f02b96371779bfb0294e92c91392707fa999c0c989 1.65kB / 1.65kB done
#5 sha256:bc3447f6ba006c2268ccab840236cd1e27502a1d9133381f17db8bfc603bc810 1.37kB / 1.37kB done
#5 CANCELED

#6 [2/7] WORKDIR /app
#6 CACHED

#7 [3/7] COPY ./requirements.txt .
#7 ERROR: failed to calculate checksum of ref 40bc7d34-f251-4a8c-9b64-40dd406c9169::va75ih9sv29d2dsuk7fewq7if: "/requirements.txt": not found
------
 > [3/7] COPY ./requirements.txt .:
------
Dockerfile:7
--------------------
   5 |     WORKDIR /app
   6 |     
   7 | >>> COPY ./requirements.txt .
   8 |     
   9 |     # apk repository
--------------------
ERROR: failed to solve: failed to compute cache key: failed to calculate checksum of ref 40bc7d34-f251-4a8c-9b64-40dd406c9169::va75ih9sv29d2dsuk7fewq7if: "/requirements.txt": not found
removing docker image...
clearing temp directory
machine already started
TEMP DIR: /tmp/tmp.ZOVp3xKEN2


Warning: Permanently added '[localhost]:3022' (ED25519) to the list of known hosts.
#0 building with "default" instance using docker driver

#1 [internal] load build definition from Dockerfile
#1 transferring dockerfile: 411B done
#1 DONE 0.1s

#2 [internal] load metadata for docker.io/library/python:3
#2 DONE 0.8s

#3 [internal] load .dockerignore
#3 transferring context: 2B done
#3 DONE 0.1s

#4 [1/4] FROM docker.io/library/python:3@sha256:3966b81808d864099f802080d897cef36c01550472ab3955fdd716d1c665acd6
#4 DONE 0.0s

#5 [2/4] WORKDIR /app
#5 CACHED

#6 [internal] load build context
#6 transferring context: 411B done
#6 DONE 0.1s

#7 [3/4] COPY . /app
#7 DONE 0.1s

#8 [4/4] RUN pip install --no-cache-dir -r requirements.txt
#8 1.480 ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'
#8 ERROR: process "/bin/sh -c pip install --no-cache-dir -r requirements.txt" did not complete successfully: exit code: 1
------
 > [4/4] RUN pip install --no-cache-dir -r requirements.txt:
1.480 ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'
------
Dockerfile:11
--------------------
   9 |     
  10 |     # Install any needed dependencies specified in requirements.txt
  11 | >>> RUN pip install --no-cache-dir -r requirements.txt
  12 |     
  13 |     # Run the repo's test suite
--------------------
ERROR: failed to solve: process "/bin/sh -c pip install --no-cache-dir -r requirements.txt" did not complete successfully: exit code: 1
removing docker image...
clearing temp directory
machine already started
TEMP DIR: /tmp/tmp.HzrgHrUZOe


Warning: Permanently added '[localhost]:3022' (ED25519) to the list of known hosts.
#0 building with "default" instance using docker driver

#1 [internal] load build definition from Dockerfile
#1 transferring dockerfile: 394B done
#1 DONE 0.1s

#2 [internal] load metadata for docker.io/library/python:3.8
#2 DONE 0.7s

#3 [internal] load .dockerignore
#3 transferring context: 2B done
#3 DONE 0.1s

#4 [1/5] FROM docker.io/library/python:3.8@sha256:01a4da15f16395a2d17dd9b673ccedcd6a6dbb4e130c8056d0d804dedac11c81
#4 DONE 0.0s

#5 [2/5] WORKDIR /app
#5 CACHED

#6 [internal] load build context
#6 transferring context: 394B done
#6 DONE 0.1s

#7 [3/5] COPY . /app
#7 DONE 0.2s

#8 [4/5] RUN pip install --no-cache-dir -r requirements.txt
#8 1.219 ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'
#8 1.349 
#8 1.349 [notice] A new release of pip is available: 23.0.1 -> 24.0
#8 1.349 [notice] To update, run: pip install --upgrade pip
#8 ERROR: process "/bin/sh -c pip install --no-cache-dir -r requirements.txt" did not complete successfully: exit code: 1
------
 > [4/5] RUN pip install --no-cache-dir -r requirements.txt:
1.219 ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'
1.349 
1.349 [notice] A new release of pip is available: 23.0.1 -> 24.0
1.349 [notice] To update, run: pip install --upgrade pip
------
Dockerfile:11
--------------------
   9 |     
  10 |     # Install any needed packages specified in requirements.txt
  11 | >>> RUN pip install --no-cache-dir -r requirements.txt
  12 |     
  13 |     # Run the test suite
--------------------
ERROR: failed to solve: process "/bin/sh -c pip install --no-cache-dir -r requirements.txt" did not complete successfully: exit code: 1
removing docker image...
clearing temp directory
machine already started
TEMP DIR: /tmp/tmp.WoRGlpxTVc


Warning: Permanently added '[localhost]:3022' (ED25519) to the list of known hosts.
#0 building with "default" instance using docker driver

#1 [internal] load build definition from Dockerfile
#1 transferring dockerfile: 591B done
#1 DONE 0.1s

#2 [internal] load metadata for docker.io/library/python:3.6-alpine
#2 DONE 0.8s

#3 [internal] load .dockerignore
#3 transferring context: 2B done
#3 DONE 0.1s

#4 [internal] load build context
#4 DONE 0.0s

#5 [1/8] FROM docker.io/library/python:3.6-alpine@sha256:579978dec4602646fe1262f02b96371779bfb0294e92c91392707fa999c0c989
#5 resolve docker.io/library/python:3.6-alpine@sha256:579978dec4602646fe1262f02b96371779bfb0294e92c91392707fa999c0c989 0.0s done
#5 sha256:8786870f287676cca49c1e1e5029467c087ad293b824fcddc489cbe2819745b2 0B / 282.15kB 0.1s
#5 sha256:579978dec4602646fe1262f02b96371779bfb0294e92c91392707fa999c0c989 1.65kB / 1.65kB done
#5 sha256:bc3447f6ba006c2268ccab840236cd1e27502a1d9133381f17db8bfc603bc810 1.37kB / 1.37kB done
#5 sha256:3a9e80fa460687aa888ebe54540132662b58a3bb1a222c3809fd412d4652eb9c 8.08kB / 8.08kB done
#5 sha256:59bf1c3509f33515622619af21ed55bbe26d24913cedbca106468a5fb37a50c3 0B / 2.82MB 0.1s
#5 CANCELED

#4 [internal] load build context
#4 transferring context: 591B done
#4 DONE 0.1s

#6 [2/8] WORKDIR /app
#6 CACHED

#7 [3/8] COPY ./requirements.txt .
#7 ERROR: failed to calculate checksum of ref 40bc7d34-f251-4a8c-9b64-40dd406c9169::v0zc70zhhxkyka1tqda54gag3: "/requirements.txt": not found
------
 > [3/8] COPY ./requirements.txt .:
------
Dockerfile:7
--------------------
   5 |     WORKDIR /app
   6 |     
   7 | >>> COPY ./requirements.txt .
   8 |     
   9 |     # apk repository
--------------------
ERROR: failed to solve: failed to compute cache key: failed to calculate checksum of ref 40bc7d34-f251-4a8c-9b64-40dd406c9169::v0zc70zhhxkyka1tqda54gag3: "/requirements.txt": not found
removing docker image...
clearing temp directory
machine already started
TEMP DIR: /tmp/tmp.dZaUxpAju9


Warning: Permanently added '[localhost]:3022' (ED25519) to the list of known hosts.
#0 building with "default" instance using docker driver

#1 [internal] load build definition from Dockerfile
#1 transferring dockerfile: 407B done
#1 DONE 0.1s

#2 [internal] load metadata for docker.io/library/python:3
#2 DONE 0.8s

#3 [internal] load .dockerignore
#3 transferring context: 2B done
#3 DONE 0.1s

#4 [1/4] FROM docker.io/library/python:3@sha256:3966b81808d864099f802080d897cef36c01550472ab3955fdd716d1c665acd6
#4 DONE 0.0s

#5 [2/4] WORKDIR /app
#5 CACHED

#6 [internal] load build context
#6 transferring context: 407B done
#6 DONE 0.1s

#7 [3/4] COPY . /app
#7 DONE 0.2s

#8 [4/4] RUN pip install --no-cache-dir -r requirements.txt
#8 1.566 ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'
#8 ERROR: process "/bin/sh -c pip install --no-cache-dir -r requirements.txt" did not complete successfully: exit code: 1
------
 > [4/4] RUN pip install --no-cache-dir -r requirements.txt:
1.566 ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'
------
Dockerfile:11
--------------------
   9 |     
  10 |     # Install any needed packages specified in requirements.txt
  11 | >>> RUN pip install --no-cache-dir -r requirements.txt
  12 |     
  13 |     # Run the repo's test suite
--------------------
ERROR: failed to solve: process "/bin/sh -c pip install --no-cache-dir -r requirements.txt" did not complete successfully: exit code: 1
removing docker image...
clearing temp directory
machine already started
TEMP DIR: /tmp/tmp.xQ94L7PQSM


Warning: Permanently added '[localhost]:3022' (ED25519) to the list of known hosts.
#0 building with "default" instance using docker driver

#1 [internal] load build definition from Dockerfile
#1 transferring dockerfile: 424B done
#1 DONE 0.1s

#2 [internal] load metadata for docker.io/library/python:3.8
#2 DONE 0.8s

#3 [internal] load .dockerignore
#3 transferring context: 2B done
#3 DONE 0.1s

#4 [1/5] FROM docker.io/library/python:3.8@sha256:01a4da15f16395a2d17dd9b673ccedcd6a6dbb4e130c8056d0d804dedac11c81
#4 DONE 0.0s

#5 [2/5] WORKDIR /app
#5 CACHED

#6 [internal] load build context
#6 transferring context: 424B done
#6 DONE 0.1s

#7 [4/5] COPY requirements.txt .
#7 ERROR: failed to calculate checksum of ref 40bc7d34-f251-4a8c-9b64-40dd406c9169::z711zriazjuyz8dc4lx2ecqm2: "/requirements.txt": not found

#8 [3/5] COPY . /app
#8 CANCELED
------
 > [4/5] COPY requirements.txt .:
------
Dockerfile:11
--------------------
   9 |     
  10 |     # Install any needed packages specified in requirements.txt
  11 | >>> copy requirements.txt .
  12 |     RUN pip install --no-cache-dir -r requirements.txt
  13 |     
--------------------
ERROR: failed to solve: failed to compute cache key: failed to calculate checksum of ref 40bc7d34-f251-4a8c-9b64-40dd406c9169::z711zriazjuyz8dc4lx2ecqm2: "/requirements.txt": not found
removing docker image...
clearing temp directory
machine already started
TEMP DIR: /tmp/tmp.s1FIBdpvPi


Warning: Permanently added '[localhost]:3022' (ED25519) to the list of known hosts.
#0 building with "default" instance using docker driver

#1 [internal] load build definition from Dockerfile
#1 transferring dockerfile:
#1 transferring dockerfile: 349B done
#1 DONE 0.2s

#2 [internal] load metadata for docker.io/library/python:3.8
#2 DONE 1.0s

#3 [internal] load .dockerignore
#3 transferring context: 2B done
#3 DONE 0.1s

#4 [1/4] FROM docker.io/library/python:3.8@sha256:01a4da15f16395a2d17dd9b673ccedcd6a6dbb4e130c8056d0d804dedac11c81
#4 DONE 0.0s

#5 [2/4] WORKDIR /app
#5 CACHED

#6 [3/4] RUN git clone <URL> .
#6 0.393 /bin/sh: 1: cannot open URL: No such file
#6 ERROR: process "/bin/sh -c git clone <URL> ." did not complete successfully: exit code: 2
------
 > [3/4] RUN git clone <URL> .:
cannot open URL: No such file
------
Dockerfile:8
--------------------
   6 |     
   7 |     # Clone the repository from the GitHub URL
   8 | >>> RUN git clone <URL> .
   9 |     
  10 |     # Install any required dependencies
--------------------
ERROR: failed to solve: process "/bin/sh -c git clone <URL> ." did not complete successfully: exit code: 2
removing docker image...
clearing temp directory
machine already started
TEMP DIR: /tmp/tmp.EUuV3EXfHl


Warning: Permanently added '[localhost]:3022' (ED25519) to the list of known hosts.
#0 building with "default" instance using docker driver

#1 [internal] load build definition from Dockerfile
#1 transferring dockerfile: 361B done
#1 DONE 0.1s

#2 [internal] load metadata for docker.io/library/python:3.8
#2 DONE 0.7s

#3 [internal] load .dockerignore
#3 transferring context: 2B done
#3 DONE 0.1s

#4 [1/5] FROM docker.io/library/python:3.8@sha256:01a4da15f16395a2d17dd9b673ccedcd6a6dbb4e130c8056d0d804dedac11c81
#4 DONE 0.0s

#5 [2/5] WORKDIR /app
#5 CACHED

#6 [3/5] RUN git clone https://github.com/your-username/your-repo.git .
#6 0.272 Cloning into '.'...
#6 0.620 fatal: could not read Username for 'https://github.com': No such device or address
#6 ERROR: process "/bin/sh -c git clone https://github.com/your-username/your-repo.git ." did not complete successfully: exit code: 128
------
 > [3/5] RUN git clone https://github.com/your-username/your-repo.git .:
0.272 Cloning into '.'...
0.620 fatal: could not read Username for 'https://github.com': No such device or address
------
Dockerfile:8
--------------------
   6 |     
   7 |     # Clone the repository
   8 | >>> RUN git clone https://github.com/your-username/your-repo.git .
   9 |     
  10 |     # Install project dependencies
--------------------
ERROR: failed to solve: process "/bin/sh -c git clone https://github.com/your-username/your-repo.git ." did not complete successfully: exit code: 128
removing docker image...
clearing temp directory
machine already started
TEMP DIR: /tmp/tmp.RDXTJV2eA3


Warning: Permanently added '[localhost]:3022' (ED25519) to the list of known hosts.
#0 building with "default" instance using docker driver

#1 [internal] load build definition from Dockerfile
#1 transferring dockerfile: 400B done
#1 DONE 0.1s

#2 [internal] load metadata for docker.io/library/python:3.8
#2 DONE 0.9s

#3 [internal] load .dockerignore
#3 transferring context: 2B done
#3 DONE 0.1s

#4 [1/4] FROM docker.io/library/python:3.8@sha256:01a4da15f16395a2d17dd9b673ccedcd6a6dbb4e130c8056d0d804dedac11c81
#4 DONE 0.0s

#5 [2/4] WORKDIR /app
#5 CACHED

#6 [internal] load build context
#6 transferring context: 400B done
#6 DONE 0.1s

#7 [3/4] COPY . /app
#7 DONE 0.1s

#8 [4/4] RUN pip install --no-cache-dir -r requirements.txt
#8 1.382 ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'
#8 1.888 
#8 1.888 [notice] A new release of pip is available: 23.0.1 -> 24.0
#8 1.888 [notice] To update, run: pip install --upgrade pip
#8 ERROR: process "/bin/sh -c pip install --no-cache-dir -r requirements.txt" did not complete successfully: exit code: 1
------
 > [4/4] RUN pip install --no-cache-dir -r requirements.txt:
1.382 ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'
1.888 
1.888 [notice] A new release of pip is available: 23.0.1 -> 24.0
1.888 [notice] To update, run: pip install --upgrade pip
------
Dockerfile:11
--------------------
   9 |     
  10 |     # Install any needed packages specified in requirements.txt
  11 | >>> RUN pip install --no-cache-dir -r requirements.txt
  12 |     
  13 |     # Run the test suite
--------------------
ERROR: failed to solve: process "/bin/sh -c pip install --no-cache-dir -r requirements.txt" did not complete successfully: exit code: 1
removing docker image...
clearing temp directory
machine already started
TEMP DIR: /tmp/tmp.pve7bQ7mcS


Warning: Permanently added '[localhost]:3022' (ED25519) to the list of known hosts.
#0 building with "default" instance using docker driver

#1 [internal] load build definition from Dockerfile
#1 transferring dockerfile: 299B done
#1 DONE 0.1s

#2 [internal] load metadata for docker.io/library/python:3.8
#2 DONE 0.9s

#3 [internal] load .dockerignore
#3 transferring context: 2B done
#3 DONE 0.1s

#4 [1/5] FROM docker.io/library/python:3.8@sha256:01a4da15f16395a2d17dd9b673ccedcd6a6dbb4e130c8056d0d804dedac11c81
#4 DONE 0.0s

#5 [2/5] WORKDIR /app
#5 CACHED

#6 [internal] load build context
#6 transferring context: 2B 0.0s done
#6 DONE 0.2s

#7 [3/5] RUN git clone https://github.com/username/repo.git .
#7 ...

#8 [4/5] COPY requirements.txt .
#8 ERROR: failed to calculate checksum of ref 40bc7d34-f251-4a8c-9b64-40dd406c9169::a0s0eq244gghukasnqm8jnygn: "/requirements.txt": not found

#7 [3/5] RUN git clone https://github.com/username/repo.git .
#7 0.462 runc run failed: container process is already dead
#7 CANCELED
------
 > [4/5] COPY requirements.txt .:
------
Dockerfile:10
--------------------
   8 |     
   9 |     # Install dependencies
  10 | >>> COPY requirements.txt .
  11 |     RUN pip install -r requirements.txt
  12 |     
--------------------
ERROR: failed to solve: failed to compute cache key: failed to calculate checksum of ref 40bc7d34-f251-4a8c-9b64-40dd406c9169::a0s0eq244gghukasnqm8jnygn: "/requirements.txt": not found
removing docker image...
clearing temp directory
machine already started
TEMP DIR: /tmp/tmp.qll6g1m3EG


Warning: Permanently added '[localhost]:3022' (ED25519) to the list of known hosts.
#0 building with "default" instance using docker driver

#1 [internal] load build definition from Dockerfile
#1 transferring dockerfile: 351B done
#1 DONE 0.1s

#2 [internal] load metadata for docker.io/library/python:3.8
#2 DONE 0.8s

#3 [internal] load .dockerignore
#3 transferring context: 2B done
#3 DONE 0.1s

#4 [1/5] FROM docker.io/library/python:3.8@sha256:01a4da15f16395a2d17dd9b673ccedcd6a6dbb4e130c8056d0d804dedac11c81
#4 DONE 0.0s

#5 [2/5] WORKDIR /app
#5 CACHED

#6 [3/5] RUN git clone https://github.com/your-username/your-repository.git .
#6 0.266 Cloning into '.'...
#6 0.612 fatal: could not read Username for 'https://github.com': No such device or address
#6 ERROR: process "/bin/sh -c git clone https://github.com/your-username/your-repository.git ." did not complete successfully: exit code: 128
------
 > [3/5] RUN git clone https://github.com/your-username/your-repository.git .:
0.266 Cloning into '.'...
0.612 fatal: could not read Username for 'https://github.com': No such device or address
------
Dockerfile:8
--------------------
   6 |     
   7 |     # Clone the repository
   8 | >>> RUN git clone https://github.com/your-username/your-repository.git .
   9 |     
  10 |     # Install project dependencies
--------------------
ERROR: failed to solve: process "/bin/sh -c git clone https://github.com/your-username/your-repository.git ." did not complete successfully: exit code: 128
removing docker image...
clearing temp directory
machine already started
TEMP DIR: /tmp/tmp.mITlzkqOWD


Warning: Permanently added '[localhost]:3022' (ED25519) to the list of known hosts.
#0 building with "default" instance using docker driver

#1 [internal] load build definition from Dockerfile
#1 transferring dockerfile: 420B done
#1 DONE 0.1s

#2 [internal] load metadata for docker.io/library/python:3.8
#2 DONE 0.8s

#3 [internal] load .dockerignore
#3 transferring context: 2B done
#3 DONE 0.1s

#4 [1/6] FROM docker.io/library/python:3.8@sha256:01a4da15f16395a2d17dd9b673ccedcd6a6dbb4e130c8056d0d804dedac11c81
#4 DONE 0.0s

#5 [2/6] WORKDIR /app
#5 CACHED

#6 [3/6] RUN git clone https://github.com/username/repo.git
#6 0.311 Cloning into 'repo'...
#6 0.711 fatal: could not read Username for 'https://github.com': No such device or address
#6 ERROR: process "/bin/sh -c git clone https://github.com/username/repo.git" did not complete successfully: exit code: 128
------
 > [3/6] RUN git clone https://github.com/username/repo.git:
0.311 Cloning into 'repo'...
0.711 fatal: could not read Username for 'https://github.com': No such device or address
------
Dockerfile:8
--------------------
   6 |     
   7 |     # Clone the repository
   8 | >>> RUN git clone https://github.com/username/repo.git
   9 |     
  10 |     # Change the working directory to the cloned repo
--------------------
ERROR: failed to solve: process "/bin/sh -c git clone https://github.com/username/repo.git" did not complete successfully: exit code: 128
removing docker image...
clearing temp directory
machine already started
TEMP DIR: /tmp/tmp.hOxcEQzcPW


Warning: Permanently added '[localhost]:3022' (ED25519) to the list of known hosts.
#0 building with "default" instance using docker driver

#1 [internal] load build definition from Dockerfile
#1 transferring dockerfile: 672B done
#1 DONE 0.1s

#2 [internal] load metadata for docker.io/library/python:3.6-alpine
#2 DONE 1.8s

#3 [internal] load .dockerignore
#3 transferring context: 2B done
#3 DONE 0.1s

#4 [1/7] FROM docker.io/library/python:3.6-alpine@sha256:579978dec4602646fe1262f02b96371779bfb0294e92c91392707fa999c0c989
#4 resolve docker.io/library/python:3.6-alpine@sha256:579978dec4602646fe1262f02b96371779bfb0294e92c91392707fa999c0c989 0.0s done
#4 ...

#5 [internal] load build context
#5 transferring context: 672B done
#5 DONE 0.1s

#4 [1/7] FROM docker.io/library/python:3.6-alpine@sha256:579978dec4602646fe1262f02b96371779bfb0294e92c91392707fa999c0c989
#4 sha256:579978dec4602646fe1262f02b96371779bfb0294e92c91392707fa999c0c989 1.65kB / 1.65kB done
#4 sha256:bc3447f6ba006c2268ccab840236cd1e27502a1d9133381f17db8bfc603bc810 1.37kB / 1.37kB done
#4 sha256:3a9e80fa460687aa888ebe54540132662b58a3bb1a222c3809fd412d4652eb9c 8.08kB / 8.08kB done
#4 sha256:59bf1c3509f33515622619af21ed55bbe26d24913cedbca106468a5fb37a50c3 0B / 2.82MB 0.2s
#4 sha256:8786870f287676cca49c1e1e5029467c087ad293b824fcddc489cbe2819745b2 0B / 282.15kB 0.2s
#4 sha256:acb0e804800ed3c10624ddeac73a6ebd3f2d6dbb03970f054233ae066cd033ba 0B / 10.18MB 0.2s
#4 sha256:59bf1c3509f33515622619af21ed55bbe26d24913cedbca106468a5fb37a50c3 1.05MB / 2.82MB 1.0s
#4 sha256:8786870f287676cca49c1e1e5029467c087ad293b824fcddc489cbe2819745b2 282.15kB / 282.15kB 1.2s done
#4 sha256:52bedcb3e853dd5d782c46d387f2af404af9ec75c2aba3a3114e9fbf913c82ed 0B / 229B 1.3s
#4 sha256:59bf1c3509f33515622619af21ed55bbe26d24913cedbca106468a5fb37a50c3 2.10MB / 2.82MB 1.8s
#4 sha256:52bedcb3e853dd5d782c46d387f2af404af9ec75c2aba3a3114e9fbf913c82ed 229B / 229B 1.8s
#4 sha256:52bedcb3e853dd5d782c46d387f2af404af9ec75c2aba3a3114e9fbf913c82ed 229B / 229B 1.8s done
#4 sha256:b064415ed3d75cd9bf462c4ea1a29aebe67dfe8fc76e672dc6bd72f29e91061b 0B / 2.21MB 2.0s
#4 sha256:59bf1c3509f33515622619af21ed55bbe26d24913cedbca106468a5fb37a50c3 2.82MB / 2.82MB 2.5s
#4 sha256:acb0e804800ed3c10624ddeac73a6ebd3f2d6dbb03970f054233ae066cd033ba 1.05MB / 10.18MB 2.5s
#4 sha256:59bf1c3509f33515622619af21ed55bbe26d24913cedbca106468a5fb37a50c3 2.82MB / 2.82MB 2.5s done
#4 extracting sha256:59bf1c3509f33515622619af21ed55bbe26d24913cedbca106468a5fb37a50c3 0.1s done
#4 extracting sha256:8786870f287676cca49c1e1e5029467c087ad293b824fcddc489cbe2819745b2 0.0s done
#4 sha256:b064415ed3d75cd9bf462c4ea1a29aebe67dfe8fc76e672dc6bd72f29e91061b 1.05MB / 2.21MB 3.8s
#4 sha256:acb0e804800ed3c10624ddeac73a6ebd3f2d6dbb03970f054233ae066cd033ba 2.10MB / 10.18MB 4.1s
#4 sha256:acb0e804800ed3c10624ddeac73a6ebd3f2d6dbb03970f054233ae066cd033ba 3.15MB / 10.18MB 5.0s
#4 sha256:b064415ed3d75cd9bf462c4ea1a29aebe67dfe8fc76e672dc6bd72f29e91061b 2.10MB / 2.21MB 5.0s
#4 sha256:b064415ed3d75cd9bf462c4ea1a29aebe67dfe8fc76e672dc6bd72f29e91061b 2.21MB / 2.21MB 5.0s done
#4 sha256:acb0e804800ed3c10624ddeac73a6ebd3f2d6dbb03970f054233ae066cd033ba 4.19MB / 10.18MB 5.6s
#4 sha256:acb0e804800ed3c10624ddeac73a6ebd3f2d6dbb03970f054233ae066cd033ba 5.24MB / 10.18MB 6.0s
#4 sha256:acb0e804800ed3c10624ddeac73a6ebd3f2d6dbb03970f054233ae066cd033ba 6.29MB / 10.18MB 6.5s
#4 sha256:acb0e804800ed3c10624ddeac73a6ebd3f2d6dbb03970f054233ae066cd033ba 7.34MB / 10.18MB 7.2s
#4 sha256:acb0e804800ed3c10624ddeac73a6ebd3f2d6dbb03970f054233ae066cd033ba 8.39MB / 10.18MB 7.7s
#4 sha256:acb0e804800ed3c10624ddeac73a6ebd3f2d6dbb03970f054233ae066cd033ba 9.44MB / 10.18MB 8.4s
#4 extracting sha256:acb0e804800ed3c10624ddeac73a6ebd3f2d6dbb03970f054233ae066cd033ba
#4 sha256:acb0e804800ed3c10624ddeac73a6ebd3f2d6dbb03970f054233ae066cd033ba 10.18MB / 10.18MB 8.7s done
#4 extracting sha256:acb0e804800ed3c10624ddeac73a6ebd3f2d6dbb03970f054233ae066cd033ba 0.4s done
#4 extracting sha256:52bedcb3e853dd5d782c46d387f2af404af9ec75c2aba3a3114e9fbf913c82ed done
#4 extracting sha256:b064415ed3d75cd9bf462c4ea1a29aebe67dfe8fc76e672dc6bd72f29e91061b
#4 extracting sha256:b064415ed3d75cd9bf462c4ea1a29aebe67dfe8fc76e672dc6bd72f29e91061b 0.2s done
#4 DONE 9.7s

#6 [2/7] WORKDIR /app
#6 DONE 0.2s

#7 [3/7] RUN apk update     && apk add --no-cache git     && git clone <repo_url> .     && pip install --no-cache-dir -r requirements.txt     && apk del git
#7 0.318 fetch https://dl-cdn.alpinelinux.org/alpine/v3.15/main/x86_64/APKINDEX.tar.gz
#7 1.470 fetch https://dl-cdn.alpinelinux.org/alpine/v3.15/community/x86_64/APKINDEX.tar.gz
#7 2.795 v3.15.11-7-g438bf8e758d [https://dl-cdn.alpinelinux.org/alpine/v3.15/main]
#7 2.796 v3.15.10-165-g73b5f3b6fbe [https://dl-cdn.alpinelinux.org/alpine/v3.15/community]
#7 2.796 OK: 15876 distinct packages available
#7 2.827 fetch https://dl-cdn.alpinelinux.org/alpine/v3.15/main/x86_64/APKINDEX.tar.gz
#7 3.232 fetch https://dl-cdn.alpinelinux.org/alpine/v3.15/community/x86_64/APKINDEX.tar.gz
#7 3.958 (1/5) Installing brotli-libs (1.0.9-r5)
#7 4.094 (2/5) Installing nghttp2-libs (1.46.0-r2)
#7 4.133 (3/5) Installing libcurl (8.5.0-r0)
#7 4.295 (4/5) Installing pcre2 (10.42-r0)
#7 4.438 (5/5) Installing git (2.34.8-r0)
#7 8.080 Executing busybox-1.34.1-r3.trigger
#7 8.084 OK: 24 MiB in 39 packages
#7 8.115 /bin/sh: can't open repo_url: no such file
#7 ERROR: process "/bin/sh -c apk update     && apk add --no-cache git     && git clone <repo_url> .     && pip install --no-cache-dir -r requirements.txt     && apk del git" did not complete successfully: exit code: 1
------
 > [3/7] RUN apk update     && apk add --no-cache git     && git clone <repo_url> .     && pip install --no-cache-dir -r requirements.txt     && apk del git:
2.827 fetch https://dl-cdn.alpinelinux.org/alpine/v3.15/main/x86_64/APKINDEX.tar.gz
3.232 fetch https://dl-cdn.alpinelinux.org/alpine/v3.15/community/x86_64/APKINDEX.tar.gz
3.958 (1/5) Installing brotli-libs (1.0.9-r5)
4.094 (2/5) Installing nghttp2-libs (1.46.0-r2)
4.133 (3/5) Installing libcurl (8.5.0-r0)
4.295 (4/5) Installing pcre2 (10.42-r0)
4.438 (5/5) Installing git (2.34.8-r0)
8.080 Executing busybox-1.34.1-r3.trigger
8.084 OK: 24 MiB in 39 packages
8.115 /bin/sh: can't open repo_url: no such file
------
Dockerfile:7
--------------------
   6 |     # Install dependencies
   7 | >>> RUN apk update \ 
   8 | >>>     && apk add --no-cache git \ 
   9 | >>>     && git clone <repo_url> . \ 
  10 | >>>     && pip install --no-cache-dir -r requirements.txt \ 
  11 | >>>     && apk del git
  12 |     
--------------------
ERROR: failed to solve: process "/bin/sh -c apk update     && apk add --no-cache git     && git clone <repo_url> .     && pip install --no-cache-dir -r requirements.txt     && apk del git" did not complete successfully: exit code: 1
removing docker image...
clearing temp directory
machine already started
TEMP DIR: /tmp/tmp.nCKPCm5ucb


Warning: Permanently added '[localhost]:3022' (ED25519) to the list of known hosts.
#0 building with "default" instance using docker driver

#1 [internal] load build definition from Dockerfile
#1 transferring dockerfile: 274B done
#1 DONE 0.1s

#2 [internal] load metadata for docker.io/library/python:3.8
#2 DONE 0.8s

#3 [internal] load .dockerignore
#3 transferring context: 2B done
#3 DONE 0.1s

#4 [1/4] FROM docker.io/library/python:3.8@sha256:01a4da15f16395a2d17dd9b673ccedcd6a6dbb4e130c8056d0d804dedac11c81
#4 DONE 0.0s

#5 [2/4] WORKDIR /app
#5 CACHED

#6 [3/4] RUN git clone https://github.com/username/repo.git .
#6 0.278 Cloning into '.'...
#6 0.670 fatal: could not read Username for 'https://github.com': No such device or address
#6 ERROR: process "/bin/sh -c git clone https://github.com/username/repo.git ." did not complete successfully: exit code: 128
------
 > [3/4] RUN git clone https://github.com/username/repo.git .:
0.278 Cloning into '.'...
0.670 fatal: could not read Username for 'https://github.com': No such device or address
------
Dockerfile:7
--------------------
   5 |     
   6 |     # Clone the repository
   7 | >>> RUN git clone https://github.com/username/repo.git .
   8 |     
   9 |     # Install dependencies
--------------------
ERROR: failed to solve: process "/bin/sh -c git clone https://github.com/username/repo.git ." did not complete successfully: exit code: 128
removing docker image...
clearing temp directory
machine already started
TEMP DIR: /tmp/tmp.f2SJDWenLn


Warning: Permanently added '[localhost]:3022' (ED25519) to the list of known hosts.
#0 building with "default" instance using docker driver

#1 [internal] load build definition from Dockerfile
#1 transferring dockerfile: 340B done
#1 DONE 0.1s

#2 [internal] load metadata for docker.io/library/python:3.9
#2 DONE 0.8s

#3 [internal] load .dockerignore
#3 transferring context: 2B done
#3 DONE 0.1s

#4 [1/4] FROM docker.io/library/python:3.9@sha256:1446afd121c574b13077f4137443114cd8085f1dade5ee63c08305b5870f2b8a
#4 DONE 0.0s

#5 [2/4] WORKDIR /app
#5 CACHED

#6 [3/4] RUN git clone <repository_url> .
#6 0.244 /bin/sh: 1: cannot open repository_url: No such file
#6 ERROR: process "/bin/sh -c git clone <repository_url> ." did not complete successfully: exit code: 2
------
 > [3/4] RUN git clone <repository_url> .:
cannot open repository_url: No such file
------
Dockerfile:8
--------------------
   6 |     
   7 |     # Clone the repository
   8 | >>> RUN git clone <repository_url> .
   9 |     
  10 |     # Install any required dependencies
--------------------
ERROR: failed to solve: process "/bin/sh -c git clone <repository_url> ." did not complete successfully: exit code: 2
removing docker image...
clearing temp directory
machine already started
TEMP DIR: /tmp/tmp.1W7WgHVdaE


Warning: Permanently added '[localhost]:3022' (ED25519) to the list of known hosts.
#0 building with "default" instance using docker driver

#1 [internal] load build definition from Dockerfile
#1 transferring dockerfile: 330B done
#1 DONE 0.1s

#2 [internal] load metadata for docker.io/library/python:3.8
#2 DONE 0.8s

#3 [internal] load .dockerignore
#3 transferring context: 2B done
#3 DONE 0.1s

#4 [1/6] FROM docker.io/library/python:3.8@sha256:01a4da15f16395a2d17dd9b673ccedcd6a6dbb4e130c8056d0d804dedac11c81
#4 DONE 0.0s

#5 [2/6] WORKDIR /app
#5 CACHED

#6 [internal] load build context
#6 transferring context: 2B 0.0s done
#6 DONE 0.2s

#7 [4/6] COPY requirements.txt ./
#7 ERROR: failed to calculate checksum of ref 40bc7d34-f251-4a8c-9b64-40dd406c9169::f46yoc7aspralb1uaop2gkh1n: "/requirements.txt": not found

#8 [3/6] RUN git clone https://github.com/your_username/your_repository.git .
#8 0.395 Cloning into '.'...
#8 0.739 fatal: could not read Username for 'https://github.com': No such device or address
#8 CANCELED
------
 > [4/6] COPY requirements.txt ./:
------
Dockerfile:10
--------------------
   8 |     
   9 |     # Install dependencies
  10 | >>> COPY requirements.txt ./
  11 |     RUN pip install --no-cache-dir -r requirements.txt
  12 |     
--------------------
ERROR: failed to solve: failed to compute cache key: failed to calculate checksum of ref 40bc7d34-f251-4a8c-9b64-40dd406c9169::f46yoc7aspralb1uaop2gkh1n: "/requirements.txt": not found
removing docker image...
clearing temp directory
machine already started
TEMP DIR: /tmp/tmp.2RuaLZ1kEX


Warning: Permanently added '[localhost]:3022' (ED25519) to the list of known hosts.
#0 building with "default" instance using docker driver

#1 [internal] load build definition from Dockerfile
#1 transferring dockerfile: 400B done
#1 DONE 0.1s

#2 [internal] load metadata for docker.io/library/python:3
#2 DONE 1.1s

#3 [internal] load .dockerignore
#3 transferring context: 2B done
#3 DONE 0.1s

#4 [1/4] FROM docker.io/library/python:3@sha256:3966b81808d864099f802080d897cef36c01550472ab3955fdd716d1c665acd6
#4 DONE 0.0s

#5 [2/4] WORKDIR /app
#5 CACHED

#6 [internal] load build context
#6 transferring context: 400B done
#6 DONE 0.1s

#7 [3/4] COPY . /app
#7 DONE 0.1s

#8 [4/4] RUN pip install --no-cache-dir -r requirements.txt
#8 1.665 ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'
#8 ERROR: process "/bin/sh -c pip install --no-cache-dir -r requirements.txt" did not complete successfully: exit code: 1
------
 > [4/4] RUN pip install --no-cache-dir -r requirements.txt:
1.665 ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'
------
Dockerfile:11
--------------------
   9 |     
  10 |     # Install any needed packages specified in requirements.txt
  11 | >>> RUN pip install --no-cache-dir -r requirements.txt
  12 |     
  13 |     # Run the test suite
--------------------
ERROR: failed to solve: process "/bin/sh -c pip install --no-cache-dir -r requirements.txt" did not complete successfully: exit code: 1
removing docker image...
clearing temp directory
machine already started
TEMP DIR: /tmp/tmp.jQrmo32Wmm


Warning: Permanently added '[localhost]:3022' (ED25519) to the list of known hosts.
#0 building with "default" instance using docker driver

#1 [internal] load build definition from Dockerfile
#1 transferring dockerfile: 378B done
#1 DONE 0.1s

#2 [internal] load metadata for docker.io/library/python:3.6
#2 DONE 1.6s

#3 [internal] load .dockerignore
#3 transferring context: 2B done
#3 DONE 0.1s

#4 [internal] load build context
#4 DONE 0.0s

#5 [1/5] FROM docker.io/library/python:3.6@sha256:f8652afaf88c25f0d22354d547d892591067aa4026a7fa9a6819df9f300af6fc
#5 resolve docker.io/library/python:3.6@sha256:f8652afaf88c25f0d22354d547d892591067aa4026a7fa9a6819df9f300af6fc 0.1s done
#5 sha256:f8652afaf88c25f0d22354d547d892591067aa4026a7fa9a6819df9f300af6fc 1.86kB / 1.86kB done
#5 sha256:54260638d07c5e3ad24c6e21fc889abbc8486a27634c0892086ff71f3f44b104 9.27kB / 9.27kB done
#5 sha256:0e29546d541cdbd309281d21a73a9d1db78665c1b95b74f32b009e0b77a6e1e3 0B / 54.92MB 0.1s
#5 sha256:d097a4907a8ec079df5ac31872359c2de510f82214c0448e926393b376d3b60d 2.22kB / 2.22kB done
#5 sha256:9b829c73b52b92b97d5c07a54fb0f3e921995a296c714b53a32ae67d19231fcd 0B / 5.15MB 0.1s
#5 ...

#4 [internal] load build context
#4 transferring context: 2B done
#4 DONE 0.1s

#6 [2/5] WORKDIR /app
#6 CACHED

#7 [3/5] RUN git clone https://github.com/jhao104/proxy_pool.git .
#7 CACHED

#8 [4/5] COPY requirements.txt ./
#8 ERROR: failed to calculate checksum of ref 40bc7d34-f251-4a8c-9b64-40dd406c9169::qof558j2t6v8hlx77uw7qipuz: "/requirements.txt": not found

#5 [1/5] FROM docker.io/library/python:3.6@sha256:f8652afaf88c25f0d22354d547d892591067aa4026a7fa9a6819df9f300af6fc
#5 CANCELED
------
 > [4/5] COPY requirements.txt ./:
------
Dockerfile:10
--------------------
   8 |     
   9 |     # Copy the requirements.txt file and install dependencies
  10 | >>> COPY requirements.txt ./
  11 |     RUN pip install --no-cache-dir -r requirements.txt
  12 |     
--------------------
ERROR: failed to solve: failed to compute cache key: failed to calculate checksum of ref 40bc7d34-f251-4a8c-9b64-40dd406c9169::qof558j2t6v8hlx77uw7qipuz: "/requirements.txt": not found
removing docker image...
clearing temp directory
machine already started
TEMP DIR: /tmp/tmp.gkasicUbtv


Warning: Permanently added '[localhost]:3022' (ED25519) to the list of known hosts.
#0 building with "default" instance using docker driver

#1 [internal] load build definition from Dockerfile
#1 transferring dockerfile: 301B done
#1 DONE 0.1s

#2 [internal] load metadata for docker.io/library/python:3.8
#2 DONE 1.2s

#3 [1/5] FROM docker.io/library/python:3.8@sha256:01a4da15f16395a2d17dd9b673ccedcd6a6dbb4e130c8056d0d804dedac11c81
#3 DONE 0.0s

#4 [2/5] WORKDIR /app
#4 CACHED

#5 [internal] load .dockerignore
#5 transferring context: 2B done
#5 DONE 0.1s

#6 exporting to image
#6 exporting layers done
#6 writing image sha256:eb49ca12a3012e2c11b328246a77f6bdb4671d511193eefeceebae1c70c93393 0.0s done
#6 naming to docker.io/library/temp_image done
#6 DONE 0.0s
Docker build completed successfully on virtual machine.
removing docker image...
clearing temp directory
